name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # Adjust this if you are working on a different branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.203'  # Adjust this to match the .NET version you are using

      - name: Publish
        run: dotnet publish Entregable8 -c Release -o build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/wwwroot
